plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/santiagoprado01/Ramos-2025-1/Diseño Avanzado App Webs/2025-1-s1-g6-t2"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]